- name: Update browserslist DB
  run: npx update-browserslist-db@latest

- name: Commit & push changes
  run: |
    git config user.name "github-actions"
    git config user.email "github-actions@github.com"
    git status
    git diff --quiet && echo "No changes" && exit 0
    git add package-lock.json
    git commit -m "chore: update browserslist DB"
    git push
